fileversion: 3

robots:
  cf1:
    enabled: true
    uri: radio://0/80/2M/E7E7E7E701
    initial_position: [0.0, 0.0, 0.0]
    type: cf21
    reference_frame: "world"

  cf2:
    enabled: true
    uri: radio://0/80/2M/E7E7E7E702
    initial_position: [1.0, 0.0, 0.0]
    type: cf21
    reference_frame: "world"

  cf3:
    enabled: true
    uri: radio://0/80/2M/E7E7E7E703
    initial_position: [2.0, 0.0, 0.0]
    type: cf21
    reference_frame: "world"

  cf4:
    enabled: true
    uri: radio://0/80/2M/E7E7E7E704
    initial_position: [3.0, 0.0, 0.0]
    type: cf21
    reference_frame: "world"

robot_types:
  cf21:
    motion_capture:
      tracking: "librigidbodytracker"
      marker: default_single_marker
      dynamics: default
    big_quad: false
    battery:
      voltage_warning: 3.8
      voltage_critical: 3.7

all:
  firmware_logging:
    enabled: true
    default_topics:
      pose:
        frequency: 10
      status:
        frequency: 1
  firmware_params:
    commander:
      enHighLevel: 1
    stabilizer:
      estimator: 2
      controller: 2
    locSrv:
      extPosStdDev: 1e-3
      extQuatStdDev: 0.5e-1
  reference_frame: "world"